# Generated by Django 5.2 on 2025-04-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="depart",
        ),
        migrations.RemoveField(
            model_name="phone",
            name="admin",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
    ]
